cmake_minimum_required(VERSION 4.3)

project(avrays)
set(OLD_BUILD_TYPE "${CMAKE_BUILD_TYPE}")
set(CMAKE_BUILD_TYPE Release)
add_subdirectory(vendor/raylib vendor/raylib)
set(CMAKE_BUILD_TYPE "${OLD_BUILD_TYPE}")
if(MSVC)
find_package(PThreads4W REQUIRED)
endif()
find_package(FFMPEG REQUIRED)
add_library(avrays STATIC)
target_sources(avrays PUBLIC avlib.h PRIVATE avlib.c)
target_include_directories(avrays PRIVATE ${FFMPEG_INCLUDE_DIRS})
target_link_directories(avrays PRIVATE ${FFMPEG_LIBRARY_DIRS})
target_link_libraries(avrays PRIVATE raylib ${FFMPEG_LIBRARIES})
if(MSVC)
target_link_libraries(avrays PRIVATE PThreads4W::PThreads4W)
endif()

add_executable(player)
target_sources(player PRIVATE main.c)
if(MSVC)
target_sources(player PRIVATE winstuff.c)
endif()
target_include_directories(player PRIVATE ${FFMPEG_INCLUDE_DIRS})
target_link_libraries(player PRIVATE avrays raylib)
