#!/usr/bin/env bash

die() {
  errcode=$?
  echo "error happened." >&2
  exit $errcode
}

makestb() {
  REMOVE_HEAD='/^\/\*\*\*/,/\*\*\*\*\//d'
  # print license header
  cat <<-EOF
	/**********************************************************************************************
	*
	*   LICENSE: zlib/libpng
	*
	*   avray is licensed under an unmodified zlib/libpng license, which is an
	* OSI-certified, BSD-like license that allows static linking with closed source
	* software:
	*
	*   Copyright (c) 2026 Jagholin (github.com/Jagholin)
	*
	*   This software is provided "as-is", without any express or implied warranty.
	* In no event will the authors be held liable for any damages arising from the
	* use of this software.
	*
	*   Permission is granted to anyone to use this software for any purpose,
	* including commercial applications, and to alter it and redistribute it
	* freely, subject to the following restrictions:
	*
	*     1. The origin of this software must not be misrepresented; you must not
	* claim that you wrote the original software. If you use this software in a
	* product, an acknowledgment in the product documentation would be appreciated
	* but is not required.
	*
	*     2. Altered source versions must be plainly marked as such, and must not
	* be misrepresented as being the original software.
	*
	*     3. This notice may not be removed or altered from any source
	* distribution.
	*
	**********************************************************************************************/
	EOF
  # print header guards
  echo "#ifndef AVRAY_STB"
  echo "#define AVRAY_STB"
  sed -e "$REMOVE_HEAD" utils.h || die
  sed -e "$REMOVE_HEAD" -e '/#include "utils.h"/d' avlib.h || die

  # add implementation
  echo "#ifdef AVRAY_IMPLEMENTATION"
  sed -e "$REMOVE_HEAD" -e '/#include "utils.h"/d' -e '/#include "avlib.h"/d' avlib.c || die
  echo "#endif // AVRAY_IMPLEMENTATION"
  echo "#endif // AVRAY_STB"
}

makestb >stb_avray.h
