/*** This file was automatically generated by make_stb script.
 *** Changes will not be saved. Edit source files instead and run make_stb again
 *** to regenerate this file.
 ***/
/**********************************************************************************************
*
*   LICENSE: zlib/libpng
*
*   avray is licensed under an unmodified zlib/libpng license, which is an
* OSI-certified, BSD-like license that allows static linking with closed source
* software:
*
*   Copyright (c) 2026 Jagholin (github.com/Jagholin)
*
*   This software is provided "as-is", without any express or implied warranty.
* In no event will the authors be held liable for any damages arising from the
* use of this software.
*
*   Permission is granted to anyone to use this software for any purpose,
* including commercial applications, and to alter it and redistribute it
* freely, subject to the following restrictions:
*
*     1. The origin of this software must not be misrepresented; you must not
* claim that you wrote the original software. If you use this software in a
* product, an acknowledgment in the product documentation would be appreciated
* but is not required.
*
*     2. Altered source versions must be plainly marked as such, and must not
* be misrepresented as being the original software.
*
*     3. This notice may not be removed or altered from any source
* distribution.
*
**********************************************************************************************/
#ifndef AVRAY_STB
#define AVRAY_STB
#ifndef UTILS_H
#define UTILS_H
#include <GL/gl.h>
#include <assert.h>
#include <libavutil/mem.h>
#include <pthread.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define UTILFUNC [[maybe_unused]] static inline

typedef struct CleanupStack {
  struct CleanupStack *pnext;
  void *what;
  void (*cb)(void *);
} CleanupStack;
static CleanupStack *cs = NULL;

static inline void avray__cleanup_mem_fn(void *d) { free(d); }
UTILFUNC void avray__cleanup_push_mem(void *memloc) {
  CleanupStack *newcs = malloc(sizeof(CleanupStack));
  *newcs = (CleanupStack){.what = memloc, .cb = &avray__cleanup_mem_fn, .pnext = cs};
  cs = newcs;
}
UTILFUNC void avray__run_cleanups() {
  while (cs) {
    CleanupStack *t = cs;
    cs->cb(cs->what);
    cs = cs->pnext;
    free(t);
  }
}

typedef struct avray__String {
  char *str;
  size_t len;
  size_t space;
} avray__String;

UTILFUNC avray__String avray__make_string() {
  char *temp = malloc(256);
  temp[0] = '\0';

  return (avray__String){.str = temp, .len = 0, .space = 256};
}

UTILFUNC void avray__free_string(avray__String s) { free(s.str); }

UTILFUNC void avray__concat_string_chars(avray__String *s, char *src) {
  size_t new_len = s->len + strlen(src);
  if (new_len >= s->space) {
    size_t new_space = s->space * 2;
    while (new_len >= new_space) {
      new_space *= 2;
    }
    s->str = realloc(s->str, new_space);
    s->space = new_space;
  }
  strcat(s->str, src);
  s->len = new_len;
}

typedef struct avray__RingBuffer {
  uint8_t *buffer;
  size_t buf_size;
  ptrdiff_t read_head, write_head;
} avray__RingBuffer;

UTILFUNC avray__RingBuffer avray__make_ringbuffer(size_t len) {
  uint8_t *temp = av_malloc(len);
  return (avray__RingBuffer){.buffer = temp, .buf_size = len};
}

UTILFUNC size_t avray__ringbuffer_len(avray__RingBuffer *rb) {
  // The size is the distance from read head to write head
  if (rb->write_head >= rb->read_head)
    return rb->write_head - rb->read_head;
  // rb->write_head < rb->read_head
  size_t result = rb->buf_size - rb->read_head;
  result += rb->write_head;
  return result;
}

UTILFUNC size_t avray__write_to_ringbuffer(avray__RingBuffer *rb, uint8_t *what, size_t len) {
  // calculate capacity
  size_t len_before = avray__ringbuffer_len(rb);
  size_t capacity = 0;
  if (rb->write_head >= rb->read_head) {
    capacity = rb->buf_size - rb->write_head;
    capacity += rb->read_head;
  } else {
    capacity = rb->read_head - rb->write_head;
  }

  if (capacity == 0) {
    return 0;
  }

  if (capacity <= len)
    return 0;
  // len = capacity;
  if (len + rb->write_head > rb->buf_size) {
    // we need to separate into 2 chunks
    // first chunk is to the end of the buffer, lets calculate its size
    ptrdiff_t first_ch_len = rb->buf_size - rb->write_head;
    ptrdiff_t second_ch_len = len - first_ch_len;
    assert(second_ch_len < rb->read_head);
    memcpy(rb->buffer + rb->write_head, what, first_ch_len);
    memcpy(rb->buffer, what + first_ch_len, second_ch_len);
    rb->write_head = second_ch_len;
    size_t len_after = avray__ringbuffer_len(rb);
    assert(len_after - len_before == len);
    return len;
  } else {
    memcpy(rb->buffer + rb->write_head, what, len);
    rb->write_head += len;
    size_t len_after = avray__ringbuffer_len(rb);
    assert(len_after - len_before == len);
    return len;
  }
}

UTILFUNC uint8_t *avray__write_ringbuffer_chunk_nocommit(avray__RingBuffer *rb, size_t len) {
  assert(rb->buf_size % len == 0);
  if (rb->write_head + len > rb->buf_size) {
    return NULL;
  }

  // dont run past read_head
  if (rb->read_head > rb->write_head && rb->write_head + len >= rb->read_head) {
    return NULL;
  }

  if (rb->write_head + len == rb->buf_size && rb->read_head == 0) {
    return NULL;
  }

  return rb->buffer + rb->write_head;
}

UTILFUNC void avray__write_ringbuffer_commit(avray__RingBuffer *rb, size_t len) {
  size_t len_before = avray__ringbuffer_len(rb);
  rb->write_head += len;
  assert(rb->write_head <= rb->buf_size);
  if (rb->write_head == rb->buf_size)
    rb->write_head = 0;
  size_t len_after = avray__ringbuffer_len(rb);
  assert(len_after - len_before == len);
}

UTILFUNC uint8_t *avray__read_ringbuffer_chunk(avray__RingBuffer *rb, size_t len) {
  size_t len_before = avray__ringbuffer_len(rb);
  // this function only works if reading doesn't cross rb's boundary
  assert(rb->buf_size % len == 0);
  if (rb->read_head + len > rb->buf_size) {
    return NULL;
  }

  // If we run past write_head, we don't have enough data
  if (rb->write_head >= rb->read_head && rb->read_head + len > rb->write_head) {
    return NULL;
  }

  uint8_t *result = rb->buffer + rb->read_head;
  rb->read_head += len;
  assert(rb->read_head <= rb->buf_size);
  if (rb->read_head == rb->buf_size)
    rb->read_head = 0;
  size_t len_after = avray__ringbuffer_len(rb);
  assert(len_before - len_after == len);
  return result;
}

UTILFUNC size_t avray__read_ringbuffer(avray__RingBuffer *rb, uint8_t *dest, size_t len) {
  size_t len_before = avray__ringbuffer_len(rb);
  size_t data_available = 0;
  if (rb->write_head >= rb->read_head) {
    data_available += rb->write_head - rb->read_head;
  } else {
    data_available += rb->buf_size - rb->read_head;
    data_available += rb->write_head;
  }

  if (data_available < len) {
    // return 0;
    len = data_available;
  }
  if (rb->read_head + len > rb->buf_size) {
    size_t first_ch_len = rb->buf_size - rb->read_head;
    size_t second_ch_len = len - first_ch_len;
    memcpy(dest, rb->buffer + rb->read_head, first_ch_len);
    memcpy(dest + first_ch_len, rb->buffer, second_ch_len);
    rb->read_head = second_ch_len;
  } else {
    memcpy(dest, rb->buffer + rb->read_head, len);
    rb->read_head += len;
  }
  size_t len_after = avray__ringbuffer_len(rb);
  assert(len_before - len_after == len);
  return len;
}

UTILFUNC void avray__free_ringbuffer(avray__RingBuffer *rb) {
  if (rb->buffer) {
    av_free(rb->buffer);
    *rb = (avray__RingBuffer){0};
  }
}

UTILFUNC void avray__ringbuffer_flush(avray__RingBuffer *rb) {
  rb->read_head = 0;
  rb->write_head = 0;
}

typedef struct TimeLine {
  void *buffer;
  size_t elem_size;
  unsigned int cursor;
  size_t len;
} TimeLine;

UTILFUNC TimeLine make_timeline(size_t elem_size, size_t length) {
  void *buf = malloc(elem_size * length);
  memset(buf, 0, elem_size * length);
  return (TimeLine){buf, elem_size, 0, length};
}

UTILFUNC void *timeline_push(TimeLine *self) {
  void *result = self->buffer + self->elem_size * self->cursor;
  self->cursor += 1;
  if (self->cursor >= self->len) {
    self->cursor = 0;
  }
  return result;
}

UTILFUNC void *timeline_get(TimeLine *self, unsigned int i) {
  size_t off = self->cursor + i;
  if (off >= self->len)
    off -= self->len;
  if (off >= self->len)
    return NULL;
  return self->buffer + self->elem_size * off;
}

UTILFUNC void free_timeline(TimeLine *self) {
  free(self->buffer);
  self->buffer = NULL;
}

typedef struct avray__LinkedQueue {
  struct avray__LinkedQueue *pnext;
  void *data;
} avray__LinkedQueue;

UTILFUNC avray__LinkedQueue *avray__make_queue() {
  avray__LinkedQueue *result = calloc(1, sizeof(avray__LinkedQueue));
  return result;
}

UTILFUNC avray__LinkedQueue *avray__queue_add(avray__LinkedQueue *q, void *data) {
  avray__LinkedQueue *left = NULL, *right = q;
  while (right->pnext) {
    left = right;
    right = right->pnext;
  }
  avray__LinkedQueue *new_link = avray__make_queue();
  new_link->data = data;
  new_link->pnext = right;
  if (left) {
    left->pnext = new_link;
    return q;
  } else {
    return new_link;
  }
}

UTILFUNC void *avray__queue_pop(avray__LinkedQueue **q) {
  void *result = (*q)->data;
  avray__LinkedQueue *head = *q;
  if (head->pnext == NULL) {
    return NULL;
  }
  (*q) = head->pnext;
  free(head);
  return result;
}

UTILFUNC void avray__queue_free(avray__LinkedQueue *q) {
  while (q) {
    avray__LinkedQueue *t = q;
    q = q->pnext;
    if (t->data) {
      free(t->data);
    }
    free(t);
  }
}

#define ERRCHECK(...)                                                          \
  if (result < 0) {                                                            \
    TraceLog(LOG_ERROR, __VA_ARGS__);                                          \
    result = RESULT_ERROR;                                                     \
    goto cleanup;                                                              \
  }
#define ERRCHECK2(val, ...)                                                    \
  if (!(val)) {                                                                \
    TraceLog(LOG_ERROR, __VA_ARGS__);                                          \
    result = RESULT_ERROR;                                                     \
    goto cleanup;                                                              \
  }
#define ERRCHECKR(res, ...)                                                    \
  if (result < 0) {                                                            \
    TraceLog(LOG_ERROR, __VA_ARGS__);                                          \
    result = (res);                                                            \
    goto cleanup;                                                              \
  }
#define ERRCHECK2R(val, res, ...)                                              \
  if (!(val)) {                                                                \
    TraceLog(LOG_ERROR, __VA_ARGS__);                                          \
    result = (res);                                                            \
    goto cleanup;                                                              \
  }

#endif // !UTILS_H
#ifndef AVLIB_H
#define AVLIB_H

#include <libavutil/pixfmt.h>
#include <libavutil/rational.h>
#include <pthread.h>
#include <raylib.h>
#include <semaphore.h>
#include <stdbool.h>

#define AVRAT_ZERO (AVRational){0, 1};

struct DecoderPrivate;

typedef enum DecoderState {
  DS_UNINIT = 0,  // default ZERO value
  DS_READY,       // after call to avray_init_decoder
  DS_STARTUP,     // filling buffers before playback
  DS_PLAYING,     // actively playing the video
  DS_FILEEOF,     // video file at EOF, but buffers aren't empty yet
  DS_FINISHED,    // File at EOF and buffers are empty. Otherwise the same as
                  // DS_READY, can call avray_open_file
  DS_SHUTDOWN,    // after call to avray_shutdown
  DS_ERROR = 100, // error condition
} DecoderState;

typedef struct RaylibObjects {
  Shader video_shader;
  Texture2D tex_luma, tex_u, tex_v;
  int y_location, u_location, v_location;
  unsigned int frame_counter;
  unsigned int bytespp;
} RaylibObjects;

typedef pthread_mutex_t MutexType;
typedef sem_t SemaphoreType;
typedef pthread_t ThreadType;

void mutex_lock(MutexType *m);
void mutex_unlock(MutexType *m);

typedef struct DecoderContext {
  struct DecoderPrivate *p;

  MutexType dc_mutex; // This mutex is locked when big changes are made to the
                      // other fields

  // Sample rate from audio codec, initialized in avray_open_file().
  unsigned int sample_rate;
  // frame rate from video codec, initialized in avray_open_file().
  unsigned int frame_rate;
  // unsigned int video_bitrate, audio_bitrate;
  // Video width from video codec, initialized in avray_open_file().
  unsigned int video_width;
  // Video height from video codec, initialized in avray_open_file().
  unsigned int video_height;
  // Pixel format used in the video stream, initialized in avray_open_file().
  enum AVPixelFormat pixel_format;

  // Video and audio time bases, initialized in avray_open_file().
  AVRational video_tb, audio_tb;
  // Timestamp of the last displayed image, updated in avray_update_textures().
  float video_timest;
  // Approximate duration in seconds, initialized in avray_open_file().
  double duration;

  TimeLine vbuffer_timeline;
  TimeLine abuffer_timeline;
  unsigned long int abytes_pulled, vbytes_pulled;
  unsigned long int abytes_written, vbytes_written;

  DecoderState state;
} DecoderContext;

#define RESULT_ERROR -1
#define RESULT_OK 0
#define RESULT_STALL 1
#define RESULT_EOF 2
#define RESULT_CANT_OPEN 3
int time_to_str(double seconds, char *buf, size_t n);

int avray_init_decoder(DecoderContext *ctx);
int avray_open_file(DecoderContext *ctx, const char *file_name);
// int avray_continue_decoding(DecoderContext *ctx);
uint8_t *avray_pull_image(DecoderContext *ctx, float *timestamp);
void avray_release_image(DecoderContext *ctx);
int avray_pull_audio(DecoderContext *ctx, void *audio_buffer,
                     unsigned int frames);
// call avray_shutdown instead
// void free_decoder_context(DecoderContext *ctx);
bool avray_is_decoder_stopped(DecoderContext *ctx);
void avray_seek_to_frame(DecoderContext *ctx, double ts);
void avray_close_file(DecoderContext *ctx);

void avray_update_timelines(DecoderContext *ctx);
void avray_shutdown(DecoderContext *ctx);
// void avray_wait_ready(DecoderContext *ctx);

int avray_init_graphics_objects(DecoderContext *ctx, RaylibObjects *objs);
int avray_free_graphics_objects(RaylibObjects *objs);
int avray_update_textures(DecoderContext *ctx, RaylibObjects *objs);
int avray_draw_video_textures(RaylibObjects *objs, Vector2 position,
                              float rotation, float scale_factor, Color tint);
void timeline_draw_ui(TimeLine tl, int x, int y, int width, int height,
                      unsigned int max, bool draw_background);
Vector2 avray_draw_debug_overlay(DecoderContext *ctx, RaylibObjects *objs,
                                 int x, int y, Vector2 *pdims,
                                 bool draw_background);
#endif // !AVLIB_H
#ifdef AVRAY_IMPLEMENTATION
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavutil/imgutils.h>
#include <libavutil/pixdesc.h>
#include <libswresample/swresample.h>
#include <pthread.h>
#include <semaphore.h>


// Size of the video buffer if the framerate is not available
#define RING_FRAMES 30

typedef pthread_mutex_t MutexType;
typedef sem_t SemaphoreType;
typedef pthread_t ThreadType;

static int avray__seek_to_frame(DecoderContext *ctx, double ts);
static int avray__exec_close_file(DecoderContext *ctx, bool called_as_cleanup);

static void avray__create_mutex(MutexType *m) { pthread_mutex_init(m, NULL); }
static void avray__create_semaphore(SemaphoreType *s, int init_value) {
  sem_init(s, 0, init_value);
}
static void avray__free_mutex(MutexType *m) { pthread_mutex_destroy(m); }
static void avray__free_semaphore(SemaphoreType *s) {
  sem_close(s);
  sem_destroy(s);
}

static void avray__semaphore_wait(SemaphoreType *s) { sem_wait(s); }
static void avray__semaphore_incr(SemaphoreType *s) { sem_post(s); }
static void avray__semaphore_get_value(SemaphoreType *s, int *val) {
  sem_getvalue(s, val);
}
void avray__mutex_lock(MutexType *m) { pthread_mutex_lock(m); }
void avray__mutex_unlock(MutexType *m) { pthread_mutex_unlock(m); }
static void avray__thread_create(ThreadType *t, void *(*thread_proc)(void *),
                          void *arg) {
  pthread_create(t, NULL, thread_proc, arg);
}
static void thread_join(ThreadType *t) { pthread_join(*t, NULL); }

int time_to_str(double seconds, char *buf, size_t n) {
  int sec = floor(seconds);
  int hours = sec / 3600;
  int mins = (sec % 3600) / 60;
  sec = sec % 60;

  return snprintf(buf, n, "%02d:%02d:%02d", hours, mins, sec);
}

typedef enum TimestampResetSM {
  TR_NONE =
      0, // To reset timestamp we need cooperation between several functions
  // It begins with avray__seek_to_frame issuing command to begin the process.
  TR_BEGIN, // Then, avray__process_audio_frame captures earliest timestamp from the
            // current frame
  TR_TIMESTAMP_CAPTURED, // Finally, pull_audio sets the timestamp to the
                         // captured one.
  TR_FINISHED,
} TimestampResetSM;

struct DecoderPrivate {
  int video_stream;
  int audio_stream;
  AVFormatContext *fmt_ctx; // Format (container) decoder context
  AVCodecContext *ctxv;     // Video decoder context
  AVCodecContext *ctxa;     // Audio decoder context
  AVPacket *pkt;
  bool pkt_populated;
  AVFrame *fr;
  bool fr_populated;
  bool frame_is_audio;
  AVFrame *fr_audio_target;
  bool fr_audio_populated;
  // AVFrame *fra;
  SwrContext *swr;

  avray__RingBuffer image_buffer;
  avray__RingBuffer audio_buffer;
  size_t image_buffer_size;
  size_t audio_buffer_size;

  bool audio_configured;
  TimestampResetSM timestamp_reset_sm;
  AVRational new_timestamp;

  avray__LinkedQueue *command_queue;

  MutexType image_buffer_mtx;
  MutexType audio_buffer_mtx;
  MutexType command_q_mtx;
  SemaphoreType sem;
  ThreadType decoder_thread;

  AVRational
      audio_pull_timestamp; // Last timestamp reached in pull_audio function
};

static const char *avray__state_str(DecoderState st) {
  switch (st) {
  case DS_READY:
    return "READY";
  case DS_PLAYING:
    return "PLAYING";
  case DS_ERROR:
    return "ERROR";
  case DS_UNINIT:
    return "UNINIT";
  case DS_STARTUP:
    return "STARTUP";
  case DS_SHUTDOWN:
    return "SHUTDOWN";
  case DS_FILEEOF:
    return "FILEEOF";
  case DS_FINISHED:
    return "FINISHED";
  default:
    return "UNKNOWN?";
  }
}

static void avray__switch_dec_state(DecoderContext *ctx, DecoderState newState) {
  TraceLog(LOG_INFO, "AVRAYS: Switching to new state: %s", avray__state_str(newState));
  ctx->state = newState;
}

typedef enum {
  COMMAND_SEEK = 1,
  COMMAND_CLOSE,
} CommandType;

struct DecoderCommand {
  int (*dispatch)(DecoderContext *, struct DecoderCommand *);
  void (*free_me)(struct DecoderCommand *);
  CommandType c_type;
  size_t struct_size;
};

struct SeekCommand {
  struct DecoderCommand cmd;
  double target;
};

struct CloseFileCommand {
  struct DecoderCommand cmd;
};

static int avray__seek_command_dispatch(DecoderContext *ctx,
                                 struct DecoderCommand *cmd) {
  struct SeekCommand *c = (struct SeekCommand *)cmd;
  return avray__seek_to_frame(ctx, c->target);
}

static void avray__free_seek_command(struct DecoderCommand *cmd) { free(cmd); }

static struct SeekCommand *avray__make_seek_command(double target) {
  struct SeekCommand *result = malloc(sizeof(struct SeekCommand));
  result->target = target;
  result->cmd.c_type = COMMAND_SEEK;
  result->cmd.dispatch = &avray__seek_command_dispatch;
  result->cmd.free_me = &avray__free_seek_command;
  result->cmd.struct_size = sizeof(struct SeekCommand);
  return result;
}

static int avray__close_command_dispatch(DecoderContext *ctx,
                                  struct DecoderCommand *_) {
  return avray__exec_close_file(ctx, false);
}

static void avray__free_close_command(struct DecoderCommand *cmd) { free(cmd); }

static struct CloseFileCommand *avray__make_close_file_command() {
  struct CloseFileCommand *result = malloc(sizeof(struct CloseFileCommand));
  result->cmd.c_type = COMMAND_CLOSE;
  result->cmd.dispatch = &avray__close_command_dispatch;
  result->cmd.free_me = &avray__free_close_command;
  result->cmd.struct_size = sizeof(struct CloseFileCommand);
  return result;
}

static void avray__add_command_to_q(avray__LinkedQueue **q, struct DecoderCommand **cmd,
                             bool collapse) {
  if (collapse) {
    avray__LinkedQueue *mq = *q;
    while (mq->pnext) {
      struct DecoderCommand *d = (struct DecoderCommand *)mq->data;
      if (d->c_type == (*cmd)->c_type) {
        // just copy command on top of the previous one and delete unneeded
        // copy.
        memcpy(d, *cmd, (*cmd)->struct_size);
        (*cmd)->free_me(*cmd);
        *cmd = NULL;
        return;
      }
    }
  }
  *q = avray__queue_add(*q, *cmd);
}

// static DecoderContext *dc;
// ThreadType decoder_thread;
static int avray_continue_decoding(DecoderContext *);
static void *avray__decode_thread(void *ctx) {
  int result = 0;
  DecoderContext *dc = (DecoderContext *)ctx;
  static int call_count = 0;
  // wait for dc to be populated
  // while (!dc) {
  //   usleep(1000);
  // }
  do {
    switch (dc->state) {
    case DS_PLAYING:
      avray__mutex_lock(&dc->p->command_q_mtx);
      struct DecoderCommand *cmd = avray__queue_pop(&dc->p->command_queue);
      avray__mutex_unlock(&dc->p->command_q_mtx);
      if (cmd) {
        TraceLog(LOG_DEBUG, "AVRAYS: Command received");
        cmd->dispatch(dc, cmd);
        cmd->free_me(cmd);
      }
      // FALLTHROUGH
    case DS_STARTUP:
      result = avray_continue_decoding(dc);
      call_count++;
      if (result < 0) {
        if (result == AVERROR_EOF) {
          // dc->state = DS_SHUTDOWN;
          avray__switch_dec_state(dc, DS_FILEEOF);
        } else {
          char err_desc[256];
          av_strerror(result, err_desc, 256);
          TraceLog(LOG_ERROR, "Call count at err: %d, err: %d(%s)", call_count,
                   result, err_desc);
          // dc->state = DS_ERROR;
          avray__switch_dec_state(dc, DS_ERROR);
        }
      }
      // exit(EXIT_FAILURE);
      break;
    default:
      usleep(1000);
      break;
    }
  } while (dc->state != DS_SHUTDOWN);
  TraceLog(LOG_INFO, "AVRAYS: Decode THREAD shutdown.");
  return NULL;
}

void avray__free_decoder_context(DecoderContext *);

int avray_init_decoder(DecoderContext *ctx) {
  // if (dc != NULL) {
  //   return RESULT_ERROR;
  // }
  *ctx = (DecoderContext){};
  ctx->p = malloc(sizeof(struct DecoderPrivate));
  memset(ctx->p, 0, sizeof(struct DecoderPrivate));
  struct DecoderPrivate *p = ctx->p;
  p->audio_pull_timestamp = AVRAT_ZERO;

  avray__create_mutex(&p->image_buffer_mtx);
  avray__create_mutex(&p->audio_buffer_mtx);
  avray__create_mutex(&p->command_q_mtx);
  avray__create_mutex(&ctx->dc_mutex);
  avray__create_semaphore(&p->sem, 1);
  // avray__create_semaphore(&p->startup_sem, 0);

  int result = RESULT_OK;
  p->swr = swr_alloc();
  ERRCHECK2(p->swr, "Cant allocate audio resampler");

  p->fr = av_frame_alloc();
  ERRCHECK2(p->fr, "Cant allocate frame");
  p->fr_audio_target = av_frame_alloc();
  ERRCHECK2(p->fr_audio_target, "Cant allocate frame");
  p->fr_audio_target->ch_layout = (AVChannelLayout)AV_CHANNEL_LAYOUT_STEREO;
  p->fr_audio_target->format = AV_SAMPLE_FMT_FLT;

  p->pkt = av_packet_alloc();
  ERRCHECK2(p->pkt, "Cant allocate packet");

  ctx->vbuffer_timeline = make_timeline(sizeof(unsigned int), 120);
  ctx->abuffer_timeline = make_timeline(sizeof(unsigned int), 120);

  ctx->video_timest = 0;

  p->command_queue = avray__make_queue();

  // dc = ctx;
  // dc->state = DS_READY;
  avray__switch_dec_state(ctx, DS_READY);
  avray__thread_create(&p->decoder_thread, &avray__decode_thread, ctx);
  return result;
cleanup:
  avray__free_decoder_context(ctx);
  return result;
}

static int avray__time_probe_seek_pts(DecoderContext *ctx, int64_t *presult) {
  struct DecoderPrivate *p = ctx->p;

  int64_t timed = AV_TIME_BASE;
  // 1. Seek to the end of the file as much as we reasonably can
  int tres = avformat_seek_file(p->fmt_ctx, -1, 0, INT64_MAX, INT64_MAX, 0);
  TraceLog(LOG_DEBUG, "AVRAYS: avray__time_probe_seek_pts(): Timeprobe returned %d",
           tres);
  int result = RESULT_ERROR;
  if (tres != 0) {
    // Seeking failed, try to recover
    goto cleanup;
  }
  AVPacket *test_p = av_packet_alloc();
  int res = 0;
  int64_t max_pts = 0;
  while (true) {
    // 2. Read incoming frames until we can't anymore
    res = av_read_frame(p->fmt_ctx, test_p);
    if (res < 0) {
      // 2a. In which case, continue with 3.
      av_packet_unref(test_p);
      break;
    }
    if (test_p->stream_index == p->video_stream) {
      if (test_p->pts == AV_NOPTS_VALUE) {
        // No PTS values present, shortcut to the end
        result = RESULT_ERROR;
        av_packet_unref(test_p);
        goto cleanup;
      }
      if (test_p->pts > max_pts) {
        // 2b. Find maximum PTS in the packets received
        max_pts = test_p->pts;
        result = RESULT_OK;
      }
    }
    av_packet_unref(test_p);
  }

  // 3. Return timestamp if successful, then cleanup.
  if (result == RESULT_OK) {
    *presult = max_pts;
  }
cleanup:
  tres = avformat_seek_file(p->fmt_ctx, -1, 0, 0, timed, 0);
  TraceLog(LOG_DEBUG, "AVRAYS: Seek back %d", tres);
  // We might not be precisely at 00:00, so receive current timestamp from
  // streams.
  p->timestamp_reset_sm = TR_BEGIN;
  av_packet_free(&test_p);
  return result;
}

int avray_open_file(DecoderContext *ctx, const char *file_name) {
  int result = RESULT_OK;
  if (ctx->state == DS_FINISHED) {
    // we still have an open file so we can close it now
    // this will also switch state to DS_READY
    result = avray__exec_close_file(ctx, false);
    ERRCHECK("Unexpected error closing a file");
  }
  assert(ctx->state == DS_READY);
  struct DecoderPrivate *p = ctx->p;
  result = avformat_open_input(&p->fmt_ctx, file_name, NULL, NULL);
  if (result != 0) {
    return RESULT_CANT_OPEN;
  }
  ERRCHECK("Can't open file");

  result = avformat_find_stream_info(p->fmt_ctx, NULL);
  ERRCHECK("Cant find stream info");

  p->video_stream =
      av_find_best_stream(p->fmt_ctx, AVMEDIA_TYPE_VIDEO, -1, -1, NULL, 0);
  ERRCHECK2R(p->video_stream >= 0, RESULT_CANT_OPEN, "Cant find video stream");
  p->audio_stream =
      av_find_best_stream(p->fmt_ctx, AVMEDIA_TYPE_AUDIO, -1, -1, NULL, 0);
  ERRCHECK2R(p->audio_stream >= 0, RESULT_CANT_OPEN, "Cant find audio stream");
  AVCodecParameters *origin_par =
      p->fmt_ctx->streams[p->video_stream]->codecpar;
  AVCodecParameters *origin_par_audio =
      p->fmt_ctx->streams[p->audio_stream]->codecpar;

  TraceLog(
      LOG_DEBUG,
      "AVRAYS: Audio sample rate: %d, bits per sample: %d, channels: %d, "
      "frame "
      "size: %d",
      origin_par_audio->sample_rate, origin_par_audio->bits_per_coded_sample,
      origin_par_audio->ch_layout.nb_channels, origin_par_audio->frame_size);
  TraceLog(LOG_DEBUG, "AVRAYS: Video frame rate: %d/%d",
           origin_par->framerate.num, origin_par->framerate.den);

  const AVCodec *codec = avcodec_find_decoder(origin_par->codec_id);
  ERRCHECK2(codec, "Can't find decoder");
  const AVCodec *audio_codec = avcodec_find_decoder(origin_par_audio->codec_id);
  TraceLog(LOG_INFO, "AVRAYS: Video decoded with %s, audio with %s",
           codec->name, audio_codec->name);
  const char *duration_method;
  switch (p->fmt_ctx->duration_estimation_method) {
  case AVFMT_DURATION_FROM_PTS: ///< Duration accurately estimated from PTSes
    duration_method = "PTS";
    break;
  case AVFMT_DURATION_FROM_STREAM: ///< Duration estimated from a stream with a
                                   ///< known duration
    duration_method = "STREAM";
    break;
  case AVFMT_DURATION_FROM_BITRATE: ///< Duration estimated from bitrate (less
                                    ///< accurate)
    duration_method = "BITRATE";
    break;
  }
  double dur_est = (double)p->fmt_ctx->duration / AV_TIME_BASE;

  char msg[128];
  time_to_str(dur_est, msg, 128);
  TraceLog(LOG_INFO, "AVRAYS: Estimated duration %lf sec(%s) from %s", dur_est,
           msg, duration_method);

  if (p->fmt_ctx->duration_estimation_method == AVFMT_DURATION_FROM_BITRATE) {
    // Duration might not be accurate, estimate it with other methods instead
    int64_t pts;
    AVRational vid_tb = p->fmt_ctx->streams[p->video_stream]->time_base;
    result = avray__time_probe_seek_pts(ctx, &pts);
    if (result == RESULT_OK) {
      dur_est = av_q2d(av_mul_q((AVRational){pts, 1}, vid_tb));
    }
  }
  avray__mutex_lock(&ctx->dc_mutex);

  ctx->duration = dur_est;

  p->ctxv = avcodec_alloc_context3(codec);
  ERRCHECK2(p->ctxv, "Cant allocate memory for decoder context");
  p->ctxa = avcodec_alloc_context3(audio_codec);
  ERRCHECK2(p->ctxa, "Cant allocate memory for audio decoder");

  result = avcodec_parameters_to_context(p->ctxv, origin_par);
  ERRCHECK("Cant initiate video codec parameters");
  result = avcodec_parameters_to_context(p->ctxa, origin_par_audio);
  ERRCHECK("Cant initiate audio codec parameters");
  p->ctxv->thread_count = 4;
  p->ctxv->thread_type = FF_THREAD_SLICE;

  result = avcodec_open2(p->ctxv, codec, NULL);
  ERRCHECK("Cant open decoder");
  result = avcodec_open2(p->ctxa, audio_codec, NULL);
  ERRCHECK("Cant open audio decoder");

  const AVPixFmtDescriptor *pix_desc = av_pix_fmt_desc_get(p->ctxv->pix_fmt);
  TraceLog(LOG_INFO, "AVRAYS: Frame is %dx%d (%s)", p->ctxv->width,
           p->ctxv->height, pix_desc->name);
  ctx->video_width = p->ctxv->width;
  ctx->video_height = p->ctxv->height;
  if (p->ctxv->framerate.num != 0) {
    ctx->frame_rate = av_q2d(p->ctxv->framerate);
  } else {
    ctx->frame_rate = av_q2d(origin_par->framerate);
  }

  p->image_buffer_size =
      av_image_get_buffer_size(p->ctxv->pix_fmt, p->ctxv->width,
                               p->ctxv->height, 16) +
      sizeof(float);

  AVRational framerate = p->ctxv->framerate;
  size_t buffer_frames = (size_t)av_q2d(framerate);
  if (framerate.den == 1 && framerate.num == 0) {
    buffer_frames = RING_FRAMES;
  }

  p->image_buffer = avray__make_ringbuffer(p->image_buffer_size * buffer_frames);

  TraceLog(LOG_DEBUG,
           "AVRAYS: Audio codec data: sample format %s, sample rate %d, "
           "bytes per sample "
           "%d",
           av_get_sample_fmt_name(p->ctxa->sample_fmt), p->ctxa->sample_rate,
           av_get_bytes_per_sample(p->ctxa->sample_fmt));
  ctx->sample_rate = p->ctxa->sample_rate;

  TraceLog(LOG_DEBUG, "AVRAYS: video Time base is %d/%d",
           p->fmt_ctx->streams[p->video_stream]->time_base.num,
           p->fmt_ctx->streams[p->video_stream]->time_base.den);
  TraceLog(LOG_DEBUG, "AVRAYS: audio Time base is %d/%d",
           p->fmt_ctx->streams[p->audio_stream]->time_base.num,
           p->fmt_ctx->streams[p->audio_stream]->time_base.den);
  ctx->video_tb = p->fmt_ctx->streams[p->video_stream]->time_base;
  ctx->audio_tb = p->fmt_ctx->streams[p->audio_stream]->time_base;

  TraceLog(LOG_DEBUG, "AVRAYS: Codec framerate: %d/%d", p->ctxv->framerate.num,
           p->ctxv->framerate.den);
  // ctx->video_framerate = p->ctxv->framerate;
  ctx->pixel_format = origin_par->format;

  // ctx->state = DS_STARTUP;
  p->audio_pull_timestamp = AVRAT_ZERO;
  avray__switch_dec_state(ctx, DS_STARTUP);
  avray__mutex_unlock(&ctx->dc_mutex);

  return RESULT_OK;
cleanup:
  avray__exec_close_file(ctx, true);
  avray__mutex_unlock(&ctx->dc_mutex);
  return result;
}

static int avray__exec_close_file(DecoderContext *ctx, bool called_as_cleanup) {
  if (ctx->state != DS_STARTUP && ctx->state != DS_PLAYING &&
      ctx->state != DS_FINISHED && ctx->state != DS_FILEEOF &&
      !called_as_cleanup) {
    return RESULT_OK;
  }
  struct DecoderPrivate *p = ctx->p;
  int result = RESULT_OK;
  // If we were called for cleanup, the mutex is already locked.
  if (!called_as_cleanup) {
    avray__mutex_lock(&ctx->dc_mutex);
  }

  avray__mutex_lock(&p->audio_buffer_mtx);
  avray__mutex_lock(&p->image_buffer_mtx);

  ctx->pixel_format = 0;
  // ctx->video_framerate = AVRAT_ZERO;

  ctx->audio_tb = AVRAT_ZERO;
  ctx->video_tb = AVRAT_ZERO;
  ctx->sample_rate = 0;
  ctx->video_timest = 0;

  ctx->abytes_pulled = ctx->vbytes_pulled = ctx->abytes_written =
      ctx->vbytes_written = 0;

  avray__free_ringbuffer(&p->image_buffer);
  avray__free_ringbuffer(&p->audio_buffer);
  p->image_buffer_size = 0;
  p->audio_buffer_size = 0;

  ctx->video_height = ctx->video_width = 0;

  if (p->ctxa)
    avcodec_free_context(&p->ctxa);
  if (p->ctxv)
    avcodec_free_context(&p->ctxv);
  // if (p->fr_audio_target) {
  //   av_frame_free(&p->fr_audio_target);
  // }

  ctx->duration = 0;
  p->audio_stream = p->video_stream = 0;
  if (p->fmt_ctx)
    avformat_close_input(&p->fmt_ctx);

  // Reset other things as well
  if (p->pkt_populated) {
    av_packet_unref(p->pkt);
    p->pkt_populated = false;
  }
  p->fr_populated = p->fr_audio_populated = false;
  p->frame_is_audio = false;
  p->audio_configured = false;
  p->timestamp_reset_sm = TR_NONE;

  // Recreate semaphore, since we don't know its exact state
  avray__free_semaphore(&p->sem);
  avray__create_semaphore(&p->sem, 1);

  avray__switch_dec_state(ctx, DS_READY);

  avray__mutex_unlock(&p->image_buffer_mtx);
  avray__mutex_unlock(&p->audio_buffer_mtx);

  if (!called_as_cleanup) {
    avray__mutex_unlock(&ctx->dc_mutex);
  }

  return result;
}

// Feeds packet pkt to video or audio decoder
static int avray__feed_codec(struct DecoderPrivate *p, int *stream) {
  if (!p->pkt_populated) {
    return RESULT_OK;
  }

  int packet_stream = p->pkt->stream_index;
  if (stream) {
    *stream = packet_stream;
  }
  int result = 0;
  if (packet_stream == p->video_stream) {
    result = avcodec_send_packet(p->ctxv, p->pkt);
  } else if (packet_stream == p->audio_stream) {
    result = avcodec_send_packet(p->ctxa, p->pkt);
  }
  av_packet_unref(p->pkt);
  p->pkt_populated = false;
  return result;
}

static int avray__send_eof2codecs(struct DecoderPrivate *p) {
  int res1 = avcodec_send_packet(p->ctxv, NULL);
  int res2 = avcodec_send_packet(p->ctxa, NULL);
  if (res1 <= res2)
    return res1;
  return res2;
}

static int avray__pull_frame(struct DecoderPrivate *p) {
  if (p->fr_populated) {
    TraceLog(LOG_DEBUG, "AVRAYS: avray__pull_frame shortcut");
    return RESULT_OK;
  }

  // Try to receive audio frame, then a video frame
  int result = avcodec_receive_frame(p->ctxa, p->fr);
  if (result == 0) {
    p->fr_populated = true;
    p->frame_is_audio = true;
    return RESULT_OK;
  }
  result = avcodec_receive_frame(p->ctxv, p->fr);
  if (result == 0) {
    p->fr_populated = true;
    p->frame_is_audio = false;
  }
  return result;
}

static void avray__signal_startup(DecoderContext *ctx) {
  if (ctx->state != DS_STARTUP)
    return;
  // avray__semaphore_incr(&ctx->p->startup_sem);
  // ctx->state = DS_PLAYING;
  avray__switch_dec_state(ctx, DS_PLAYING);
}

static int avray__process_video_frame(DecoderContext *ctx) {
  struct DecoderPrivate *p = ctx->p;
  if (!p->fr_populated) {
    return RESULT_OK;
  }
  int result = RESULT_OK;
  uint8_t *write_loc =
      avray__write_ringbuffer_chunk_nocommit(&p->image_buffer, p->image_buffer_size);
  if (write_loc == NULL) {
    return RESULT_STALL;
  }
  avray__mutex_lock(&p->image_buffer_mtx);
  av_image_copy_to_buffer(write_loc + sizeof(float),
                          p->image_buffer_size - sizeof(float),
                          (uint8_t const *const *)p->fr->data, p->fr->linesize,
                          p->ctxv->pix_fmt, p->ctxv->width, p->ctxv->height, 1);

  AVRational video_time =
      av_mul_q(av_make_q(p->fr->best_effort_timestamp, 1), ctx->video_tb);
  (*(float *)write_loc) = (float)av_q2d(video_time);

  avray__write_ringbuffer_commit(&p->image_buffer, p->image_buffer_size);
  ctx->vbytes_written += p->image_buffer_size;
  avray__mutex_unlock(&p->image_buffer_mtx);
  p->fr_populated = false;
  return result;
}

static void avray__init_audio_buffer(struct DecoderPrivate *p) {
  assert(p->audio_buffer_size == 0);
  // TODO: check that p->fr and p->fr_audio_target are both valid audio frames
  assert(p->fr_audio_target->sample_rate != 0 && p->fr->sample_rate != 0);

  p->audio_buffer_size = p->fr_audio_target->nb_samples * sizeof(float) * 2;
  // How much is 1 second of sound? sample_rate samples
  size_t target_audio_ring_size = p->fr->sample_rate * sizeof(float) * 2;
  // This is now also the bitrate for sound
  size_t size_adj =
      p->audio_buffer_size - target_audio_ring_size % p->audio_buffer_size;
  target_audio_ring_size += size_adj;
  size_t audio_ring_size = target_audio_ring_size;
  // If the ringbuffer size is too small compared to what raylib
  // expects(4096 bytes) make it bigger.
  if (audio_ring_size < 4096 * 8) {
    audio_ring_size = 4096 * 8;
    // It still has to divide by audio_buffer_size.
    size_adj = p->audio_buffer_size - audio_ring_size % p->audio_buffer_size;
    audio_ring_size += size_adj;
  }
  p->audio_buffer = avray__make_ringbuffer(audio_ring_size);
  TraceLog(LOG_INFO, "AVRAYS: Audio buffer size is now %zu",
           p->audio_buffer.buf_size);
}

static void avray__init_swr_ifneeded(DecoderContext *ctx) {
  struct DecoderPrivate *p = ctx->p;
  // p->fr has to be an audio frame here
  if (p->audio_configured /*&&
      p->fr->nb_samples == p->fr_audio_target->nb_samples*/)
    return;

  /*if (p->audio_configured) {
    // If it was configured already, we have to reconfigure a few things
    av_frame_unref(p->fr_audio_target);

    p->fr_audio_target->ch_layout = (AVChannelLayout)AV_CHANNEL_LAYOUT_STEREO;
    p->fr_audio_target->format = AV_SAMPLE_FMT_FLT;
  }*/

  assert(ctx->sample_rate == p->fr->sample_rate);
  // ctx->sample_rate = p->fr->sample_rate;
  p->fr_audio_target->sample_rate = ctx->sample_rate;

  int result = swr_config_frame(p->swr, p->fr_audio_target, p->fr);
  TraceLog(LOG_DEBUG, "AVRAYS: SWR (re) initialized");
  assert(result == 0);

  p->audio_configured = true;
}

static int avray__process_audio_frame(DecoderContext *ctx) {
  struct DecoderPrivate *p = ctx->p;
  int result = RESULT_OK;
  bool fresh_frame = false;
  if (!p->fr_audio_populated) {
    avray__init_swr_ifneeded(ctx);
    assert(p->fr_populated);
    result = swr_convert_frame(p->swr, p->fr_audio_target, p->fr);
    // assert(swr_get_delay(p->swr, ctx->sample_rate) == 0);
    ERRCHECK("Cant convert audio frame");
    p->fr_populated = false;
    p->fr_audio_populated = true;
    fresh_frame = true;
  }

  if (p->audio_buffer_size == 0) {
    avray__init_audio_buffer(p);
  }

  avray__mutex_lock(&p->audio_buffer_mtx);
  size_t frame_size = p->fr_audio_target->nb_samples * sizeof(float) * 2;
  // fwrite(p->fr->data[0], 1, p->fr->nb_samples * 8, tempfile);
  // fflush(tempfile);
  size_t bytes_written = avray__write_to_ringbuffer(
      &p->audio_buffer, p->fr_audio_target->data[0], frame_size);
  ctx->abytes_written += bytes_written;

  if (bytes_written == 0) {
    // No space left in the buffer, indicate STALL condition
    avray__mutex_unlock(&p->audio_buffer_mtx);
    return RESULT_STALL;
  }

  if (p->timestamp_reset_sm == TR_BEGIN && fresh_frame) {
    // Get new timestamp from the audio frame
    p->new_timestamp =
        av_mul_q((AVRational){p->fr->best_effort_timestamp, 1}, ctx->audio_tb);
    TraceLog(LOG_DEBUG, "AVRAYS: Captured timestamp: %d / %d",
             p->new_timestamp.num, p->new_timestamp.den);
    p->timestamp_reset_sm = TR_TIMESTAMP_CAPTURED;
  }
  p->fr_audio_populated = false;
  avray__mutex_unlock(&p->audio_buffer_mtx);
cleanup:
  return result;
}

int avray_continue_decoding(DecoderContext *ctx) {
  if (ctx->state != DS_PLAYING && ctx->state != DS_STARTUP) {
    return RESULT_OK;
  }
  struct DecoderPrivate *p = ctx->p;

  // 1. Wait for decoding semaphore to release
  avray__semaphore_wait(&p->sem);
  avray__semaphore_incr(&p->sem);

  int result = RESULT_OK;

  // If we have any data in SWR buffer, try to drain it first
  if (p->audio_configured) {
    if (!p->fr_audio_populated && swr_get_delay(p->swr, ctx->sample_rate) > 0) {
      result = swr_convert_frame(p->swr, p->fr_audio_target, NULL);
      ERRCHECK("error extracting extra audio data");
      p->fr_audio_populated = true;
      p->frame_is_audio = true;
    }
  }

  // 2. If we already have a frame waiting from previous iteration, just use it
  if (!(p->fr_populated || p->fr_audio_populated)) {
    // 2a. try pulling a frame
    result = avray__pull_frame(p);

    while (result == AVERROR(EAGAIN)) {
      // 2b. frame doesn't exist, so we feed the decoder with the next packet
      assert(p->pkt_populated == false);
      result = av_read_frame(p->fmt_ctx, p->pkt);
      if (result < 0) {
        avray__send_eof2codecs(p);
      } else {
        p->pkt_populated = true;
        result = avray__feed_codec(p, NULL);
        ERRCHECK("Feed codec error");
      }
      // 2c. try pulling a frame again if we dont have it yet
      result = avray__pull_frame(p);
    }
  }
  if (result != RESULT_OK) {
    goto cleanup;
  }

  // 3. Process the frame that we received
  if (p->frame_is_audio) {
    result = avray__process_audio_frame(ctx);
  } else {
    result = avray__process_video_frame(ctx);
  }
  // 4. If the buffer is full, signal stall condition
  if (result == RESULT_STALL) {
    // 4a. If we are in a startup state, signal that we decoded enough.
    avray__signal_startup(ctx);
    avray__semaphore_wait(&p->sem);
    goto cleanup;
  }

cleanup:
  return result;
}

static void avray__try_unlock_decoder_sem(DecoderContext *ctx) {
  int sem_value;
  struct DecoderPrivate *p = ctx->p;
  avray__semaphore_get_value(&p->sem, &sem_value);
  if (sem_value == 0) {
    // we can advance semaphore if both buffers are less than 80% empty
    if (avray__ringbuffer_len(&p->image_buffer) < 0.8 * p->image_buffer.buf_size &&
        avray__ringbuffer_len(&p->audio_buffer) < 0.8 * p->audio_buffer.buf_size) {
      avray__semaphore_incr(&p->sem);
    }
  }
}

static void avray__try_move_to_finished_state(DecoderContext *ctx) {
  if (ctx->state != DS_FILEEOF)
    return;
  if (avray__ringbuffer_len(&ctx->p->audio_buffer) == 0 &&
      avray__ringbuffer_len(&ctx->p->image_buffer) == 0) {
    avray__switch_dec_state(ctx, DS_FINISHED);
  }
}

uint8_t *avray_pull_image(DecoderContext *ctx, float *timestamp) {
  struct DecoderPrivate *p = ctx->p;

  avray__mutex_lock(&p->image_buffer_mtx);
  // File could have been closed before we locked the mutex, or something else
  // might've happened
  if (ctx->state != DS_PLAYING && ctx->state != DS_FILEEOF) {
    // Even in this case we expect avray_release_image to be called,
    // so we don't unlock the mutex here.
    return NULL;
  }
  // printf("pull_image called\n");
  uint8_t *data = avray__read_ringbuffer_chunk(&p->image_buffer, p->image_buffer_size);
  if (data == NULL) {
    avray__try_move_to_finished_state(ctx);
    return data;
  }
  ctx->vbytes_pulled += p->image_buffer_size;
  *timestamp = *(float *)data;
  return data + sizeof(float);
}

void avray_release_image(DecoderContext *ctx) {
  avray__try_unlock_decoder_sem(ctx);
  avray__mutex_unlock(&ctx->p->image_buffer_mtx);
}

int avray_pull_audio(DecoderContext *ctx, void *audio_buffer,
                     unsigned int frames) {
  // printf("pull_audio %d called\n", frames);
  struct DecoderPrivate *p = ctx->p;
  if (ctx->state != DS_PLAYING && ctx->state != DS_FILEEOF) {
    return 0;
  }
  avray__mutex_lock(&p->audio_buffer_mtx);
  // File could've been closed while we were waiting for mutex to release.
  // So we have to check the state again.
  if (ctx->state != DS_PLAYING && ctx->state != DS_FILEEOF) {
    avray__mutex_unlock(&p->audio_buffer_mtx);
    return 0;
  }
  if (!p->audio_configured) {
    avray__mutex_unlock(&p->audio_buffer_mtx);
    return 0;
  }
  size_t bytes_to_read = frames * 2 * sizeof(float);
  int result = avray__read_ringbuffer(&p->audio_buffer, audio_buffer, bytes_to_read);
  ctx->abytes_pulled += result;
  avray__try_unlock_decoder_sem(ctx);
  const int bytes_per_frame = sizeof(float) * 2;
  if (p->timestamp_reset_sm == TR_TIMESTAMP_CAPTURED) {
    p->audio_pull_timestamp = p->new_timestamp;
    p->timestamp_reset_sm = TR_FINISHED;
  } else {
    p->audio_pull_timestamp =
        av_add_q(p->audio_pull_timestamp,
                 av_make_q(result / bytes_per_frame, ctx->sample_rate));
  }
  if (result == 0) {
    avray__try_move_to_finished_state(ctx);
  }
  avray__mutex_unlock(&p->audio_buffer_mtx);
  return result;
}

static int avray__seek_to_frame(DecoderContext *ctx, double ts) {
  int64_t time = floor(ts * AV_TIME_BASE);
  int64_t time_dt = AV_TIME_BASE;

  struct DecoderPrivate *p = ctx->p;
  avray__mutex_lock(&p->audio_buffer_mtx);
  avray__mutex_lock(&p->image_buffer_mtx);
  TraceLog(LOG_DEBUG, "AVRAYS: seeking to %ld", time);
  int result = avformat_seek_file(p->fmt_ctx, -1, time - time_dt, time,
                                  time + time_dt, 0);
  TraceLog(LOG_DEBUG, "AVRAYS: Seek file (+-1) returns %d", result);
  if (result != 0) {
    result = avformat_seek_file(p->fmt_ctx, -1, time - 5 * time_dt, time,
                                time + 5 * time_dt, 0);
    TraceLog(LOG_DEBUG, "AVRAYS: Seek file (+-5) returns %d", result);
  }
  if (result != 0) {
    result = avformat_seek_file(p->fmt_ctx, -1, time - 10 * time_dt, time,
                                time + 10 * time_dt, 0);
    TraceLog(LOG_DEBUG, "AVRAYS: Seek file (+-10) returns %d", result);
  }
  if (result != 0) {
    result = avformat_seek_file(p->fmt_ctx, -1, time - 20 * time_dt, time,
                                time + 20 * time_dt, 0);
    TraceLog(LOG_DEBUG, "AVRAYS: Seek file (+-20) returns %d", result);
  }
  if (result != 0) {
    result = avformat_seek_file(p->fmt_ctx, -1, 0, time, INT64_MAX, 0);
    TraceLog(LOG_DEBUG, "AVRAYS: Seek file (+-INF) returns %d", result);
  }
  if (result != 0) {
    avray__mutex_unlock(&p->image_buffer_mtx);
    avray__mutex_unlock(&p->audio_buffer_mtx);
    return result;
  }
  avcodec_flush_buffers(p->ctxv);
  avcodec_flush_buffers(p->ctxa);
  if (ctx->state != DS_STARTUP) {
    // repurpose "startup" tech here
    assert(ctx->state == DS_PLAYING);
    // ctx->state = DS_STARTUP;
    avray__switch_dec_state(ctx, DS_STARTUP);
    // decrease semaphore count, it should now become 0
    // avray__semaphore_wait(&p->startup_sem);
  }
  avray__ringbuffer_flush(&p->audio_buffer);
  avray__ringbuffer_flush(&p->image_buffer);
  p->timestamp_reset_sm = TR_BEGIN;
  p->new_timestamp = (AVRational){0, 1};
  p->fr_audio_populated = false;
  p->fr_populated = false;
  ctx->video_timest = 0;
  if (p->pkt_populated) {
    p->pkt_populated = false;
    av_packet_unref(p->pkt);
  }
  avray__try_unlock_decoder_sem(ctx);
  avray__mutex_unlock(&p->image_buffer_mtx);
  avray__mutex_unlock(&p->audio_buffer_mtx);
  return RESULT_OK;
}

void avray_seek_to_frame(DecoderContext *ctx, double ts) {
  struct DecoderPrivate *p = ctx->p;
  avray__mutex_lock(&p->command_q_mtx);

  struct SeekCommand *cmd = avray__make_seek_command(ts);
  TraceLog(LOG_DEBUG, "AVRAYS: Command seek added");
  // p->command_queue = avray__queue_add(p->command_queue, cmd);
  avray__add_command_to_q(&p->command_queue, (struct DecoderCommand **)&cmd, true);

  avray__mutex_unlock(&p->command_q_mtx);
}

void avray_close_file(DecoderContext *ctx) {
  struct DecoderPrivate *p = ctx->p;
  avray__mutex_lock(&p->command_q_mtx);

  struct CloseFileCommand *cmd = avray__make_close_file_command();
  TraceLog(LOG_DEBUG, "AVRAYS: Command closefile added");
  // p->command_queue = avray__queue_add(p->command_queue, cmd);
  avray__add_command_to_q(&p->command_queue, (struct DecoderCommand **)&cmd, true);

  avray__mutex_unlock(&p->command_q_mtx);
}

bool avray_is_decoder_stopped(DecoderContext *ctx) {
  return ctx->state == DS_SHUTDOWN /* || ctx->state == DS_FINISHED*/ ||
         ctx->state == DS_ERROR;
}

void avray__free_decoder_context(DecoderContext *ctx) {
  // TODO: join the thread here?
  // for now we just assume that the thread was either joined, or never started
  struct DecoderPrivate *p = ctx->p;

  if (p->command_queue) {
    avray__queue_free(p->command_queue);
    p->command_queue = NULL;
  }

  avray__free_semaphore(&p->sem);
  // avray__free_semaphore(&p->startup_sem);
  avray__free_mutex(&p->command_q_mtx);
  avray__free_mutex(&p->audio_buffer_mtx);
  avray__free_mutex(&p->image_buffer_mtx);
  avray__free_mutex(&ctx->dc_mutex);
  avray__free_ringbuffer(&p->image_buffer);
  avray__free_ringbuffer(&p->audio_buffer);
  if (p->pkt) {
    av_packet_free(&p->pkt);
  }
  if (p->fr_audio_target) {
    av_frame_free(&p->fr_audio_target);
  }
  if (p->fr) {
    av_frame_free(&p->fr);
  }
  if (p->ctxa) {
    avcodec_free_context(&p->ctxa);
  }
  if (p->ctxv) {
    avcodec_free_context(&p->ctxv);
  }
  if (p->swr) {
    swr_free(&p->swr);
  }
  if (p->fmt_ctx) {
    avformat_close_input(&p->fmt_ctx);
  }
  free(p);
  ctx->p = NULL;
}

void avray_update_timelines(DecoderContext *ctx) {
  struct DecoderPrivate *p = ctx->p;
  unsigned int *tl_loc = (unsigned int *)timeline_push(&ctx->abuffer_timeline);
  if (p->audio_buffer_size > 0) {
    *tl_loc = avray__ringbuffer_len(&p->audio_buffer) * 100 / p->audio_buffer.buf_size;
  } else {
    *tl_loc = 0;
  }
  tl_loc = (unsigned int *)timeline_push(&ctx->vbuffer_timeline);
  if (p->image_buffer.buf_size > 0) {
    *tl_loc = avray__ringbuffer_len(&p->image_buffer) * 100 / p->image_buffer.buf_size;
  } else {
    *tl_loc = 0;
  }
}

// void avray_initialize() { avray__thread_create(&decoder_thread, &avray__decode_thread); }
// void avray_wait_ready(DecoderContext *ctx) {
//   avray__semaphore_wait(&ctx->p->startup_sem);
// }

void avray_shutdown(DecoderContext *ctx) {
  // printf("Thread shutdown isn't implemented yet\n");
  avray__switch_dec_state(ctx, DS_SHUTDOWN);
  // Release semaphore sem so that avray_continue_decoding could proceed
  avray__semaphore_incr(&ctx->p->sem);
  thread_join(&ctx->p->decoder_thread);
  avray__free_decoder_context(ctx);
}

// Raylib specific things
#include <raylib.h>

const char *fs_yuv420p10 = "#version 130\n"

                           "in vec2 fragTexCoord;"
                           "out vec4 finalColor;"
                           "uniform sampler2D tex_luma;"
                           "uniform sampler2D tex_u;"
                           "uniform sampler2D tex_v;"

                           "float samplet(sampler2D t) {"
                           "   vec4 smp = texture(t, fragTexCoord);"
                           "   float res = smp.r * 0.25 + smp.a * 64.0;"
                           "   return res; }"

                           "void main() {"
                           "   float smp = samplet(tex_luma);"
                           "   float luma_f = smp;"
                           "   smp = samplet(tex_u);"
                           "   float u_f = smp - 0.5;"
                           "   smp = samplet(tex_v);"
                           "   float v_f = smp - 0.5;"

                           "   luma_f = 1.1643*(luma_f - 0.0625);"
                           "   float r=luma_f+1.5958*v_f;"
                           "   float g=luma_f-0.39173*u_f-0.81290*v_f;"
                           "   float b=luma_f+2.017*u_f;"
                           "   finalColor=vec4(r, g, b, 1.0);"
                           "}";

// shader code adopted from
// https://stackoverflow.com/questions/30191911/is-it-possible-to-draw-yuv422-and-yuv420-texture-using-opengl
const char *fs_yuv420p = "#version 130 \n"
                         "in vec2 fragTexCoord;"
                         "in vec4 fragColor;"
                         "out vec4 finalColor;"
                         "uniform sampler2D tex_luma;"
                         "uniform sampler2D tex_u;"
                         "uniform sampler2D tex_v;"
                         "void main() {"
                         "   float luma = texture(tex_luma, fragTexCoord).r;"
                         "   float u = texture(tex_u, fragTexCoord).r;"
                         "   float v = texture(tex_v, fragTexCoord).r;"
                         "   luma=1.1643*(luma-0.0625);"
                         "   u=u-0.5;"
                         "   v=v-0.5;"
                         "   float r=luma+1.5958*v;"
                         "   float g=luma-0.39173*u-0.81290*v;"
                         "   float b=luma+2.017*u;"
                         "   finalColor=vec4(r, g, b, 1.0);"
                         "}";

int avray_init_graphics_objects(DecoderContext *ctx, RaylibObjects *objs) {
  *objs = (RaylibObjects){};
  PixelFormat pf;
  const char *shader_code;

  switch (ctx->pixel_format) {
  case AV_PIX_FMT_YUV420P:
    pf = PIXELFORMAT_UNCOMPRESSED_GRAYSCALE;
    objs->bytespp = 1;
    shader_code = fs_yuv420p;
    break;
  case AV_PIX_FMT_YUV420P10LE:
    pf = PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA;
    objs->bytespp = 2;
    shader_code = fs_yuv420p10;
    break;
  default:
    TraceLog(LOG_ERROR, "AVRAYS: Dont recognize pix fmt %d", ctx->pixel_format);
    return RESULT_ERROR;
  }

  Image frame_img = GenImageColor(ctx->video_width, ctx->video_height, BLUE);
  ImageFormat(&frame_img, pf);
  objs->tex_luma = LoadTextureFromImage(frame_img);

  // Make another texture with half height and width for UV channels
  UnloadImage(frame_img);
  frame_img = GenImageColor(ctx->video_width / 2, ctx->video_height / 2, GREEN);
  ImageFormat(&frame_img, pf);
  objs->tex_u = LoadTextureFromImage(frame_img);
  UnloadImage(frame_img);
  frame_img = GenImageColor(ctx->video_width / 2, ctx->video_height / 2, GREEN);
  ImageFormat(&frame_img, pf);
  objs->tex_v = LoadTextureFromImage(frame_img);
  UnloadImage(frame_img);

  objs->video_shader = LoadShaderFromMemory(NULL, shader_code);
  objs->y_location = GetShaderLocation(objs->video_shader, "tex_luma");
  objs->u_location = GetShaderLocation(objs->video_shader, "tex_u");
  objs->v_location = GetShaderLocation(objs->video_shader, "tex_v");

  return RESULT_OK;
}

int avray_free_graphics_objects(RaylibObjects *objs) {
  UnloadShader(objs->video_shader);
  UnloadTexture(objs->tex_luma);
  UnloadTexture(objs->tex_u);
  UnloadTexture(objs->tex_v);
  return RESULT_OK;
}

int avray_update_textures(DecoderContext *ctx, RaylibObjects *objs) {
  // If the TimestampResetSM is active, the ts is probably not reliable
  struct DecoderPrivate *p = ctx->p;
  if (p->timestamp_reset_sm != TR_NONE &&
      p->timestamp_reset_sm != TR_FINISHED) {
    // So we can just return prematurely, no updates needed
    return RESULT_OK;
  }
  double ts = av_q2d(p->audio_pull_timestamp);
  // A special case is when the we are in DS_FILEEOF state, and no more audio
  // data in the buffers are present. In this state, we will have to override
  // video_timest<ts checks so that we can flush the rest of the video frames.
  bool ts_check_override =
      ctx->state == DS_FILEEOF && avray__ringbuffer_len(&p->audio_buffer) == 0;
  if (ts_check_override)
    TraceLog(LOG_DEBUG, "AVRAYS: avray_update_textures() override triggered");
  if (ctx->video_timest < ts || ts_check_override) {
    uint8_t *image_buff = NULL;
    while (ctx->video_timest < ts || ts_check_override) {
      uint8_t *prev_image = image_buff;
      image_buff = avray_pull_image(ctx, &ctx->video_timest);
      if (image_buff == NULL) {
        // If we ran out of frames, just show the last one no matter the
        // timestamp.
        image_buff = prev_image;
        break;
      }
      objs->frame_counter++;
      // If we are going for the next iteration, have to make sure to
      // release_image.
      if (ctx->video_timest < ts || ts_check_override) {
        avray_release_image(ctx);
      }
    }
    if (image_buff) {
      // If tex_luma isn't initialized, assume that we couldn't find shaders for
      // the current pixelformat, so we can't display video
      if (IsTextureValid(objs->tex_luma)) {
        UpdateTexture(objs->tex_luma, image_buff);
        image_buff += ctx->video_height * ctx->video_width * objs->bytespp;
        UpdateTexture(objs->tex_u, image_buff);
        image_buff += ctx->video_height * ctx->video_width * objs->bytespp / 4;
        UpdateTexture(objs->tex_v, image_buff);
      }
    }
    avray_release_image(ctx);
  }

  return RESULT_OK;
}

int avray_draw_video_textures(RaylibObjects *objs, Vector2 position,
                              float rotation, float scale_factor, Color tint) {
  // If tex_luma isn't initialized, assume that we couldn't find shaders for
  // the current pixelformat, so we can't display video
  if (!IsTextureValid(objs->tex_luma)) {
    return RESULT_OK;
  }
  BeginShaderMode(objs->video_shader);
  {
    SetShaderValueTexture(objs->video_shader, objs->y_location, objs->tex_luma);
    SetShaderValueTexture(objs->video_shader, objs->u_location, objs->tex_u);
    SetShaderValueTexture(objs->video_shader, objs->v_location, objs->tex_v);

    // DrawTexture(frame_tex, 0, 0, WHITE);
    DrawTextureEx(objs->tex_luma, position, rotation, scale_factor, tint);
  }
  EndShaderMode();
  return RESULT_OK;
}

void timeline_draw_ui(TimeLine tl, int x, int y, int width, int height,
                      unsigned int max, bool draw_background) {
  const unsigned short int font_size = 20;
  char text_buffer[80];
  snprintf(text_buffer, 16, "%d", max);
  int text_width = MeasureText(text_buffer, font_size);
  int zero_width = MeasureText("0", font_size);
  int max_text_width = text_width;
  if (zero_width > max_text_width)
    max_text_width = zero_width;
  if (draw_background) {
    DrawRectangle(x - 2, y - 2, width + 4, height + 4,
                  (Color){.r = 40, .g = 40, .b = 40, .a = 190});
  }
  DrawText(text_buffer, x + max_text_width - text_width + 1, y + 1, font_size,
           WHITE);
  DrawText("0", x + max_text_width - zero_width + 1, y + height - font_size + 1,
           font_size, WHITE);
  int gstart_x = x + max_text_width + 8;
  float segm_size_x = (width - max_text_width - 8) / (float)(tl.len - 1);
  DrawLine(gstart_x, y, gstart_x, y + height, GREEN);
  DrawLine(gstart_x, y + height, x + width, y + height, GREEN);
  DrawLine(gstart_x, y, x + width, y, GREEN);

  Vector2 *line_points = calloc(tl.len, sizeof(Vector2));
  unsigned int min_sample = max;
  unsigned int max_sample = 0;
  unsigned int avg = 0;
  for (unsigned int i = 0; i < tl.len; ++i) {
    unsigned int sample = *(unsigned int *)timeline_get(&tl, i);
    avg += sample;
    if (sample < min_sample)
      min_sample = sample;
    if (sample > max_sample)
      max_sample = sample;
    line_points[i].x = gstart_x + i * segm_size_x;
    line_points[i].y = y + height - (float)sample * height / max;
  }
  avg /= tl.len;

  snprintf(text_buffer, 80, "min:%d max:%d avg:%d", min_sample, max_sample,
           avg);
  DrawText(text_buffer, gstart_x + 8, y + height - font_size - 2, font_size,
           WHITE);
  DrawLineStrip(line_points, tl.len, BLUE);
  free(line_points);
}

Vector2 avray_draw_debug_overlay(DecoderContext *ctx, RaylibObjects *objs,
                                 int x, int y, Vector2 *pdims,
                                 bool draw_background) {
  struct DecoderPrivate *p = ctx->p;
  const unsigned int LINEHEIGHT = 25;
  const unsigned int FONTSIZE = 20;
  Vector2 dims = {};
  if (pdims) {
    dims = *pdims;
    if (draw_background) {
      DrawRectangleV((Vector2){x, y}, dims,
                     (Color){.r = 40, .g = 40, .b = 40, .a = 190});
    }
  }
  int start_y = y;
  int text_width = 0;
  timeline_draw_ui(ctx->abuffer_timeline, x, y, 300, 80, 100, false);
  y += 100;
  timeline_draw_ui(ctx->vbuffer_timeline, x, y, 300, 80, 100, false);
  y += 100;
  if (dims.x < 300)
    dims.x = 300;

  char msg[128], msga[128];
  double audio_ts_double = av_q2d(p->audio_pull_timestamp);
  snprintf(msg, sizeof(msg), "atime: %.2f vtime: %.2f d: %.2f f: %d",
           audio_ts_double, ctx->video_timest,
           fabs(audio_ts_double - ctx->video_timest), objs->frame_counter);

  int tw = MeasureText(msg, FONTSIZE);
  if (tw > text_width)
    text_width = tw;
  DrawText(msg, x, y, FONTSIZE, WHITE);
  y += LINEHEIGHT;
  snprintf(msg, sizeof(msg), "abytes: %ld written: %ld", ctx->abytes_pulled,
           ctx->abytes_written);
  tw = MeasureText(msg, FONTSIZE);
  if (tw > text_width)
    text_width = tw;
  DrawText(msg, x, y, FONTSIZE, WHITE);
  y += LINEHEIGHT;
  snprintf(msg, sizeof(msg), "vbytes: %ld, written: %ld", ctx->vbytes_pulled,
           ctx->vbytes_written);
  tw = MeasureText(msg, FONTSIZE);
  if (tw > text_width)
    text_width = tw;
  DrawText(msg, x, y, FONTSIZE, WHITE);
  y += LINEHEIGHT;

  if (p) {
    snprintf(msg, sizeof(msg), "abuffer: %zu vbuffer: %zu",
             avray__ringbuffer_len(&p->audio_buffer),
             avray__ringbuffer_len(&p->image_buffer));
    tw = MeasureText(msg, FONTSIZE);
    if (tw > text_width)
      text_width = tw;
    DrawText(msg, x, y, FONTSIZE, WHITE);
    y += LINEHEIGHT;
  }
  time_to_str(ctx->duration, msga, sizeof(msga));
  snprintf(msg, sizeof(msg), "Duration: %s", msga);
  tw = MeasureText(msg, FONTSIZE);
  if (tw > text_width)
    text_width = tw;
  if (dims.x < text_width)
    dims.x = text_width;
  DrawText(msg, x, y, FONTSIZE, WHITE);
  y += LINEHEIGHT;
  if (dims.y < y - start_y)
    dims.y = y - start_y;
  if (pdims)
    *pdims = dims;
  return dims;
}
#endif // AVRAY_IMPLEMENTATION
#endif // AVRAY_STB
